### ISSUE TITLE
Steam Input support

### ISSUE THREAD

**Issue by arendjr** [HouraiTeahouse/bevy-steamworks#10]
I might have overlooked it, but is it correct this library currently doesn't offer support for the Steam Input API? If I want to create a PR for Steam Input support, where would I start?

Thanks!

**Comment by arendjr** [comment]
Thanks! At this point I can confirm I can access the `Input` type from the `steamworks` crate now :) Once I can confirm I can actually do something useful with it, I'll be happy to create a PR.

I did notice there is also an `Input` type in the `bevy::prelude` already, so maybe it might make sense to rename it in the re-export? It was trivial to work-around anyway, so no showstopper either way.

**Comment by TrustNoOneElse** [comment]
From my perspective it would be a user implementation, if they need to include both, then they rename it with _as_ how they want it or use explicit naming.
