### ISSUE TITLE
Need Crates Release

### ISSUE THREAD

**Issue by Braymatter** [HouraiTeahouse/bevy-steamworks#18]
Hi There, just a quick heads up it looks like the migration is done on the repo, and the compat table is updated. 

Crates.io is still showing .7 as the latest version, could we get a publish soon?

**Comment by james7132** [comment]
I'm really sorry this has taken so long. I've been absolutely swamped IRL. I'll cut a release soon.

**Comment by james7132** [comment]
0.8 is up! https://crates.io/crates/bevy-steamworks/0.8.0
