### ISSUE TITLE
bevy-steamworks 0.9 not published

### ISSUE THREAD

**Issue by chipsenkbeil** [HouraiTeahouse/bevy-steamworks#28]
Looks like version 0.9 hasn't been released yet? I was following the documentation to use with bevy 0.12.

Any idea when 0.9 will be published? Or did I miss something?

**Comment by james7132** [comment]
Sorry for the huge delay on this, and I know that this is basically blocked until Bevy's 0.13 release, but it should be on crates.io now. 0.10 should be out as soon as Bevy 0.13 is available.
